---
title: "The influence of entry regulation on labour market formalization"
subtitle: "ECON 807 Macroeconomic Theory & Policy Project Proposal"
author: "Daniel Sánchez Pazmiño"
date: "`r format(as.Date('2023-02-07'), '%B %d, %Y')`"
mainfont: Latin Modern Roman
sansfont: Latin Modern Roman
bibliography: references.bib
csl: apa.csl
format: pdf
knitr:
  opts_chunk: 
    echo: false
    message: false
---

# Introduction

It is well understood that informal work -legal but informal economic activities which occur outside the government's regulatory capabilities [@Sassen.1994] - can hinder economic development. On one hand, informal firms reduce the amount of taxes that can be collected by governments. Further, these businesses tend to remain small and inefficient. Additionally, workers in the informal sector usually lack access to social security and other employment benefits, and tend to earn lower wages after controlling for skills. Informality is also related to bigger gender gaps, higher inequality, lower education and several other factors which worsen economic outcomes [@Delechat2020]. Further, the informal economy has been characterized with poorly defined work spaces, unsafe and unsanitary working conditions, inconsistent pay, long working hours and a lack of access to markets, financial services, work training, and technology [@IloND]. 

I propose an empirical framework to test the relationship between the reduction of entry regulation on the formalization of the labour market in post-pandemic Ecuador. This setting is particularly useful for testing this kind of relationship due to the introduction of an unexpected reform in May 2020 which significantly reduced entry regulation for firms [@CaminoMogro.2022]. I present the use of a regression discontinuiy in time (RDiT) design to investigate the causal effect of the reform on the creation of formal jobs at the province level.

While less present in the developed world, informality seems to be very prevalent in developing countries, where it represents a third of low and middle-income countries' economic activity [@Delechat2020]; in the world, the informal economy is reported to comprise more than half of the labour force and more than 90% of micro and small enterprises. Latin America is one of the regions with the most prevalent level of informality, as it often is the only option of work for several workers on the lower end of the wealth distribution [Oviedo.2009]. At the macroeconomic level, informality could be regarded as one consequence of poor institutions, which have been shown to be significant factors for growth [@Acemoglu.2001, @RafaelLaPorta.1997, @Glaeser.2004]. For its effect on inequality and its potential to be a channel for the propagation of monetary and fiscal policy [@Alberola.2020], informality is relevant at both the microeconomic and macroeconomic level.

The desire for the formalization of the economy is well understood on the economy, especially considering that the impact on economic activity due to COVID-19 has increased informality worldwide [@ILO.2022]. However, the policy angle to this issue is subtle, given that the causes and effects of informality are difficult to document and understand completely. Among others, some policy approaches have focused on the role of governments in providing incentives for formalization. One approach is to design tax systems that minimize distortions in the market [@Bardey.2019] as well as reducing the costs of formalization by reducing entry regulation for firms. The reasoning behind the effectiveness of this type of policy is that, as proposed by [@MauricioPrado.2011], firms who are less productive endogenously choose to operate in the informal due to the costs of entry (red tape cost) and the proportional taxation in the formal sector. While larger firms might be able to supercede the cost of formalization, smaller, less productive firms will not.

# Institutional background

Ecuador is a middle income country located in upper South America next to Colombia and Peru. After its full dollarization in 2000, the country saw an economic surge between 2007-2014 as a result of high oil prices and a relatively indebted government [@Weisbrot.2017]. However, after a sharp decline in oil prices and the COVID-19 pandemic, the country seems to be unable to return to its pre-pandemic or pre-2014 levels, with employment indicators at an all-time low. 

However, informality and underemployment in this labour market have been shown to be historically high [@Meneses.2021; @Chavez.2012; @Mendoza.2020]. It has been determined that minimum wage increases in Ecuador (which have been frequent and substantial) have had virtually no effect on employment levels due to high-level of non-compliance and informality in the labour market [@Canelas.2014]. Further, Ecuador has been shown to have one of the most cumbersome labour market legislations in the region [@MacIsaac.1997], whose effect is attenuated by smaller base earnings over which benefits are paid, which suggests a correlation between lower wages and higher amount of labour market regulation. 

Two key policies have been passed in Ecuador which have considerably affected the labour market and may have had an impact on its formalization. In 2008, regulations increased to prohibit outsourcing of several types and in 2020, some regulations were removed to smooth the impact of COVID-19 on businesses. However, there is no research that has studied the causal effect of these policies on labour market formalization. 

Not only the labour market is highly regulated in the country: the business environment in Ecuador is complicated for firms. Ecuador constantly ranks very low in terms of property rights, judicial transparency and economic freedom. Its low standing in economic freedom responds to a flawed and corrupt judiciary, characterized by inefficiency and difficulty to start a business [@Euromonitor.2022]. Further, an unstable economic environment after the election of the conservative Guillermo Lasso not long after a decade-long leftist regime has taken its toll on the government's financing capabilities. 

This political instability has also made the deregulation of the labour market difficult to discuss in the legislative branch: only one set of market-friendyl policies set forth by the new president have been passed, the labour market reform being immediately rejected by a strong majority in Congress. Given the difficulty to pass any kind of labour-related policy, other types of reforms which indirectly target the labour market would be welcome. The present analysis attempts to evaluate a policy like this one, which was not directly aimed to enhance employment, but still could cause an effect if companies with informal employees decide to formalize job contracts after entering the formal sector of the economy. The policy reform allowed a new type of legal business to exist, the *Sociedad de Accciones Simplificada* (SAS), which also exists in several other countries in the region. This type of business is known to be much less burdensome than other types of companies like anonymous societies or limited liability companies. Specifically, a SAS business type can be created with considerably lower monetary and time costs (notarization, registering, etc.) as well as with lower amounts of capital contributions. It is sensible to believe that the reform was unexpected and exogeneous since, while the law that allowed for this reform came into force in early 2020, the law did not specifically plan for the creation of this type of business, only allowed for its creation under the Ecuadorian corporate law [@CaminoMogro.2022].

# Literature review

The literature on informality is extensive. The theoretical framework points to informality being an endogenous decision, where firms with low productivity often prefer to remain informal, the size of the firm often being an important determinant of this decision [@Delechat2020; @MauricioPrado.2011; @ElianeElBadaoui.2010]. The fact that informality is an endogenous decision makes informality difficult to define in a specific setting; many informal workers are not officially registered and may not report their activities accurately [Oviedo.2009]. 

Apart from the consensus finding that informality reduces growth and developmental outcomes, in the macroeconomic context, it has been shown that informality lowers TFP and increases output volatility and may produce significant input misallocation [@Leyva.2020]. Further, informal jobs have been found to respond heavily to changes in formal employment [Leyva.2020]. This allows me to use formal jobs data, which is easier to obtain and is usually not sensitive to its definition, as are informal jobs. Further, @Lambert.2020 proposes that informality plays a shock-absorbing role due that it limits movements in the employed-unemployed margin. This is very relevant to the Ecuadorian case, as the country often shows a relatively low rate of unemployment which is deemed to be uninformative due to the prevalence of underemployment [@LaTorre.2017].

Research on Ecuadorian informality is limited and has often focused on the effect of exogenous shocks on measurements of informality, notably the effects of a significant earthquake in 2016 [@Mendoza.2020] and also of Venezuelan Migration [@Olivieri.2022], both finding positive effects on informality. It is determined that poverty and informality are jointly determined, where informal workers often come from low-education and income backgrounds. 

Further, the informal labour market is mainly supply-led but it is so heterogenously: low-skilled workers often have no choice to work informally, while better educated workers sometimes choose to operate informally [@Canelas.2019]. The minimum wage seems to produce no clear effect on informality due to high non-compliance [@Canelas.2014]. A firm size wage premium has been shown to appear across developing countries, which @ElianeElBadaoui.2010 proposes that responds to informality. Ecuador has proven this theoretical prediction of formal firms often paying more to their employees due to them being larger [@MacIsaac.1997]. On the firm side, it is determined that the endogenous choice of sector is also present in Ecuador [@Medvedev.2016]. Further, @CaminoMogro.2022 find causal evidence that the SAS reform did produce significant business creation, which means it can be assumed that the reform was effective in formalizing/creating businesses.

Estimating the size and nature of the informal economy and to assess the impact of policies aimed at reducing informality is difficult, however, one common idea that has come up as a policy angle is reducing distortions for businesses by simplifying entry regulation to facilitate formal entry for businesses. These type of policies have been implemented widely across Latin America as well as in Europe, which have had positive results [@Oviedo.2009]. To my knowledge there has been no research which links these type of policies, aimed at business formalization, to labour market formalization, most likely because labour market formalization is often tackled through specific types of policy across the world. 

Given the complicated political environment for enacting labour market policy I've referred to before, as well as the possibility that even with significant reform labour market formalization is modest, it is useful to look at the SAS reform for the Ecuadorian case. The intuition behind the successfulness of these policies would come from an implication of @ElianeElBadaoui.2010, which is that if companies who decide to operate formally and thus more likely to be caught defaulting on labour costs, upon a change in entry costs a greater number of companies who formalize will also formalize their workers. I would then expect that my empirical analysis yields a positive effect of the reform on formal employment. If policies which work around the difficulty of enacting labour market deregulation prove to produce spillover effects in the labour market, politically unstable countries like Ecuador could find ways of fostering economic growth through better institutions with alternative policy methods, which would expand the existing policy toolset to tackle informality.

# References
